- name: Install Access point related packages
  tags: accesspoint
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - dnsmasq
  - hostapd

- name: Ignore wlan0 from dhcpcd
  tags: accesspoint
  lineinfile:
    path: /etc/dhcpcd.conf
    line: denyinterfaces wlan0

- name: Copy hostapd.conf
  tags: accesspoint
  template: dest=/etc/hostapd/hostapd.conf src=hostapd.conf.j2

- name: Set up hostapd config
  tags: accesspoint
  lineinfile:
    path: /etc/default/hostapd
    line: DAEMON_CONF="/etc/hostapd/hostapd.conf"

- name: Copy network interfaces
  tags: accesspoint
  copy: src=interfaces
        dest=/etc/network/interfaces
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Restore eth0
  tags: accesspoint
  copy: src=70-persistent-net.rules
        dest=/etc/udev/rules.d/70-persistent-net.rules
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Copy dnsmasq config
  tags: accesspoint
  copy: src=dnsmasq.conf
        dest=/etc/dnsmasq.conf
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Set up ip forward
  tags: accesspoint
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1

- name: Copy network interfaces
  tags: accesspoint
  copy: src=iptables.ipv4.nat
        dest=/etc/iptables.ipv4.nat
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Restore iptables rules during boot
  tags: accesspoint
  lineinfile:
    path: /etc/rc.local
    insertbefore: '^exit 0'
    state: present
    line: iptables-restore < /etc/iptables.ipv4.nat
