- name: Install mandatory packages to compile Python 3
  tags: [ python3 ]
  apt:
    state: present
    update-cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
  vars:
    packages:
      - build-essential
      - tk-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libdb5.3-dev
      - libgdbm-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - zlib1g-dev
      - libffi-dev


- name: Download Python source
  tags: [ python3 ]
  get_url:
    url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: "/usr/local/src/Python-{{ python_version }}.tgz"
    mode: '0644'


- name: Unarchive Python source
  tags: [ python3 ]
  unarchive:
    src: "/usr/local/src/Python-{{ python_version }}.tgz"
    dest: /usr/local/src
    creates: "/usr/local/src/Python-{{ python_version }}/README.rst"


- name: Configure Python
  tags: [ python3 ]
  command: chdir="/usr/local/src/Python-{{ python_version }}" ./configure


- name: Compile Python
  tags: [ python3 ]
  command: chdir="/usr/local/src/Python-{{ python_version }}" make -j4


- name: Install python3 to /usr/local/bin
  tags: [ python3 ]
  command: chdir="/usr/local/src/Python-{{ python_version }}" sudo make altinstall
